### ISSUE TITLE
The pysolid package is not available on conda-forge for "osx-arm64"

### ISSUE THREAD

**Issue by EJFielding** [insarlab/PySolid#64]
I was running a MintPy installation with conda (`conda install -c conda-forge --file ~/tools/MintPy/requirements.txt`), and it failed to find the `pysolid` package in conda-forge for my M1 Mac:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - pysolid
 
Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

```

**Comment by scottstanie** [comment]
Hi Eric,
I'm currently trying to get the conda package migrated over so that it's available on osc-arm (M1 chips): https://github.com/conda-forge/pysolid-feedstock/pull/13 
The extra work is because conda doesn't (yet) automatically make an ARM version, but hopefully they can help resolve the issue soon. 

To test on my ARM mac, I've been cloning pysolid and running `pip install -e .` after getting the dependencies

**Comment by scottstanie** [comment]
Hopefully was closed by https://github.com/conda-forge/pysolid-feedstock/pull/13 for M1 or M2 chips

**Comment by EJFielding** [comment]
Thanks! I verified that `pysolid` now installs from `conda-forge` on my M1 Mac.
